server:
  port: 6678
spring:
  application:
    name: service-provider-consul
  cloud:
    consul:
      host: 192.168.6.151
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        register-health-check: true
