spring:
  application:
    name: service-zuul
server:
  port: 8767
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    preferIpAddress: true
    health-check-url-path: /application
  client:
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 20
    serviceUrl:
      defaultZone: http://root:123@localhost:8762/eureka/,http://root:123@localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 5
zuul:
  routes:
    #http://localhost:2103/biancheng/abc 浏览器输入 会跳转到http://c.biancheng.net
    #http://localhost:8767/service-consumer-feign/callHello
    #biancheng:
     # path: /biancheng/**
     # url: http://c.biancheng.net

