server:
  port: 8764
  servlet:
    context-path: /
spring:
  application:
    name: service-consumer
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    preferIpAddress: true
    health-check-url-path: /application
  client:
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 20
    serviceUrl:
      defaultZone: http://root:123@localhost:8762/eureka/,http://root:123@localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 5

